version: '3'
services:
  resellers-mariadb:
    image: mariadb:10.6
    container_name: resellers-mariadb
    expose:
      - "3306"
    volumes:
      - ./resources/resellers-local-environment/mariadb-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    networks:
      - resellers-network

  eatceed-backend:
    image: hwangdaesun/resellers-dev:latest
    container_name: resellers-spring
    ports:
      - 8080:8080
    depends_on:
      - resellers-mariadb
    env_file:
      - .env
    networks:
      - resellers-network
    restart:
      on-failure


networks:
  resellers-network: