use resellers;

CREATE TABLE `MEMBER_TB` (
    `MEMBER_PK` BIGINT AUTO_INCREMENT,
    `MEMBER_NAME` VARCHAR(255) NOT NULL,
    `CREATED_DATE`    datetime(6)  NOT NULL,
    `UPDATED_DATE`    datetime(6)  NOT NULL,
    `MEMBER_ACCOUNT_NUMBER` VARCHAR(255) NOT NULL,
    `MEMBER_BANK_NAME` VARCHAR(255),
    `MEMBER_CONTACT` VARCHAR(255),
     PRIMARY KEY (`MEMBER_PK`)
) ENGINE=InnoDB;

CREATE TABLE `PRODUCT_TB` (
      `PRODUCT_PK` BIGINT AUTO_INCREMENT,
      `CREATED_DATE`    datetime(6)  NOT NULL,
      `UPDATED_DATE`    datetime(6)  NOT NULL,
      `PRODUCT_DESCRIPTION` VARCHAR(255) NOT NULL,
      `PRODUCT_NAME` VARCHAR(255) NOT NULL,
      `PRODUCT_PRICE` INT NOT NULL,
      `PRODUCT_SELLER` BIGINT NOT NULL,
      `PRODUCT_IS_SOLD` bit(1) NOT NULL,
      `PRODUCT_DEFECT` VARCHAR(255) NOT NULL,
      PRIMARY KEY (`PRODUCT_PK`)
) ENGINE=InnoDB;

CREATE TABLE `MATERIAL_TB` (
   `MATERIAL_PK` BIGINT AUTO_INCREMENT,
   `CREATED_DATE`    datetime(6)  NOT NULL,
   `UPDATED_DATE`    datetime(6)  NOT NULL,
   `MATERIAL_ITEM_TYPE` VARCHAR(255),
    `MATERIAL_CONTACT` VARCHAR(255),
   `MEMBER_FK` BIGINT,
   `PRODUCT_FK` BIGINT,
   PRIMARY KEY (`MATERIAL_PK`),
   FOREIGN KEY (`PRODUCT_FK`) REFERENCES `PRODUCT_TB`(`PRODUCT_PK`),
   FOREIGN KEY (`MEMBER_FK`) REFERENCES `MEMBER_TB`(`MEMBER_PK`)
) ENGINE=InnoDB;


CREATE TABLE `IMAGE_TB` (
    `IMAGE_PK` BIGINT AUTO_INCREMENT,
    `CREATED_DATE`    datetime(6)  NOT NULL,
    `UPDATED_DATE`    datetime(6)  NOT NULL,
    `PRODUCT_FK` BIGINT,
    PRIMARY KEY (`IMAGE_PK`),
    FOREIGN KEY (`PRODUCT_FK`) REFERENCES `PRODUCT_TB`(`PRODUCT_PK`)
) ENGINE=InnoDB;

CREATE TABLE `TRADE_TB` (
    `TRADE_PK`BIGINT AUTO_INCREMENT,
    `CREATED_DATE`    datetime(6)  NOT NULL,
    `UPDATED_DATE`    datetime(6)  NOT NULL,
    `TRADE_CONFIRM` bit(1) NOT NULL,
    `TRADE_QUANTITY` INT NOT NULL,
    `PRODUCT_FK` BIGINT,
    `MEMBER_FK` BIGINT,
    PRIMARY KEY (`TRADE_PK`),
    FOREIGN KEY (`PRODUCT_FK`) REFERENCES `PRODUCT_TB`(`PRODUCT_PK`),
    FOREIGN KEY (`MEMBER_FK`) REFERENCES `MEMBER_TB`(`MEMBER_PK`)
) ENGINE=InnoDB;

