-- Use resellers database
USE resellers;

set foreign_key_checks = 0;
truncate IMAGE_TB;
truncate MATERIAL_TB;
truncate PRODUCT_TB;
truncate MEMBER_TB;
truncate TRADE_TB;
set foreign_key_checks = 1;

-- Insert members into MEMBER_TB
INSERT INTO MEMBER_TB
VALUES (1, '이진혁', TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '98102214801017',
        '기업은행', '010-2293-5028'),
       (2, '황대선', TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '1231231231', '기업은행',
        '010-1212-1212');

-- Insert products into PRODUCT_TB
INSERT INTO PRODUCT_TB
VALUES (1, TIMESTAMPADD(WEEK , -12, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명', '상품이름', 200000, 0,
        '상품결함', 1),
       (2, TIMESTAMPADD(WEEK , -11, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명2', '상품이름2', 200000, 0,
        '상품결함', 1),
       (3, TIMESTAMPADD(WEEK , -10, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명3', '상품이름3', 250000, 0,
        '상품결함', 1),
       (4, TIMESTAMPADD(WEEK , -9, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명4', '상품이름4', 300000, 0,
        '상품결함', 1),
         (5, TIMESTAMPADD(WEEK , -8, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명5', '상품이름5', 350000, 0,
        '상품결함', 1),
         (6, TIMESTAMPADD(WEEK , -7, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명6', '상품이름6', 400000, 0,
        '상품결함', 1),
         (7, TIMESTAMPADD(WEEK , -6, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명7', '상품이름7', 350000, 0,
        '상품결함', 1),
         (8, TIMESTAMPADD(WEEK , -5, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명8', '상품이름8', 380000, 0,
        '상품결함', 1),
         (9, TIMESTAMPADD(WEEK , -4, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명9', '상품이름9', 278500, 0,
        '상품결함', 1),
         (10, TIMESTAMPADD(WEEK , -3, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명10', '상품이름10', 500000, 0,
        '상품결함', 1),
         (11, TIMESTAMPADD(WEEK , -2, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명11', '상품이름11', 480000, 0,
        '상품결함', 1),
         (12, TIMESTAMPADD(WEEK , -1, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명12', '상품이름12', 380000, 0,
        '상품결함', 1);

-- Insert materials into MATERIAL_TB
INSERT INTO MATERIAL_TB
VALUES (1, TIMESTAMPADD(WEEK , -12, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '냉장고/냉동고', '010-2293-5028',
        1, 1),
       (2, TIMESTAMPADD(WEEK , -11, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '냉장고/냉동고', '010-1212-1212',
        2, 2),
       (3, TIMESTAMPADD(WEEK , -10, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '냉장고/냉동고', '010-2293-5028',
        1, 3),
         (4, TIMESTAMPADD(WEEK , -9, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '냉장고/냉동고', '010-2293-5028',
        1, 4),
         (5, TIMESTAMPADD(WEEK , -8, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '냉장고/냉동고', '010-2293-5028',
        1, 5),
         (6, TIMESTAMPADD(WEEK , -7, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '냉장고/냉동고', '010-2293-5028',
        1, 6),
         (7, TIMESTAMPADD(WEEK , -6, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '냉장고/냉동고', '010-2293-5028',
        1, 7),
         (8, TIMESTAMPADD(WEEK , -5, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '냉장고/냉동고', '010-2293-5028',
        1, 8),
         (9, TIMESTAMPADD(WEEK , -4, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '냉장고/냉동고', '010-2293-5028',
        1, 9),
         (10, TIMESTAMPADD(WEEK , -3, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '냉장고/냉동고', '010-2293-5028',
        1, 10),
         (11, TIMESTAMPADD(WEEK , -2, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '냉장고/냉동고', '010-2293-5028',
        1, 11),
         (12, TIMESTAMPADD(WEEK , -1, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '냉장고/냉동고', '010-2293-5028'
        , 1, 12);


-- Insert images into IMAGE_TB
INSERT INTO IMAGE_TB
VALUES (1, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'이진혁', 1),
       (2, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'이윤성', 1),
       (3, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'황대선', 1);

-- Insert trades into TRADE_TB
INSERT INTO TRADE_TB
VALUES (1, TIMESTAMPADD(WEEK , -12, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 0, 20, '냉장고/냉동고', 1, 2),
       (2, TIMESTAMPADD(WEEK , -11, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 0, 20, '냉장고/냉동고', 2, 2),
         (3, TIMESTAMPADD(WEEK , -10, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 0, 20, '냉장고/냉동고', 3, 2),
         (4, TIMESTAMPADD(WEEK , -9, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 0, 20, '냉장고/냉동고', 4, 2),
         (5, TIMESTAMPADD(WEEK , -8, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 0, 20, '냉장고/냉동고', 5, 2),
         (6, TIMESTAMPADD(WEEK , -7, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 0, 20, '냉장고/냉동고', 6, 2),
         (7, TIMESTAMPADD(WEEK , -6, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 0, 20, '냉장고/냉동고', 7, 2),
         (8, TIMESTAMPADD(WEEK , -5, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 0, 20, '냉장고/냉동고', 8, 2),
         (9, TIMESTAMPADD(WEEK , -4, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 0, 20, '냉장고/냉동고', 9, 2),
         (10, TIMESTAMPADD(WEEK , -3, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 0, 20, '냉장고/냉동고', 10, 2),
         (11, TIMESTAMPADD(WEEK , -2, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 0, 20, '냉장고/냉동고', 11, 2),
         (12, TIMESTAMPADD(WEEK , -1, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 0, 20, '냉장고/냉동고', 12, 2);
