-- Use resellers database
USE resellers;

set foreign_key_checks = 0;
truncate IMAGE_TB;
truncate MATERIAL_TB;
truncate PRODUCT_TB;
truncate MEMBER_TB;
truncate TRADE_TB;
set foreign_key_checks = 1;

-- Insert members into MEMBER_TB
INSERT INTO MEMBER_TB
VALUES (1, '이진혁', TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '98102214801017',
        '기업은행', '010-2293-5028'),
       (2, '황대선', TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '1231231231', '기업은행',
        '010-1212-1212');

-- Insert products into PRODUCT_TB
INSERT INTO PRODUCT_TB
VALUES (1, TIMESTAMPADD(WEEK , -12, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명', '상품이름', 200000, 0,
        '상품결함', 2),
       (2, TIMESTAMPADD(WEEK , -11, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명2', '상품이름2', 200000, 0,
        '상품결함', 2),
       (3, TIMESTAMPADD(WEEK , -10, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명3', '상품이름3', 250000, 0,
        '상품결함', 2),
       (4, TIMESTAMPADD(WEEK , -9, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명4', '상품이름4', 300000, 0,
        '상품결함', 2),
         (5, TIMESTAMPADD(WEEK , -8, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명5', '상품이름5', 350000, 0,
        '상품결함', 2),
         (6, TIMESTAMPADD(WEEK , -7, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명6', '상품이름6', 400000, 0,
        '상품결함', 2),
         (7, TIMESTAMPADD(WEEK , -6, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명7', '상품이름7', 350000, 0,
        '상품결함', 2),
         (8, TIMESTAMPADD(WEEK , -5, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명8', '상품이름8', 380000, 0,
        '상품결함', 2),
         (9, TIMESTAMPADD(WEEK , -4, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), '상품설명9', '상품이름9', 278500, 0,
        '상품결함', 2);

-- Insert materials into MATERIAL_TB
INSERT INTO MATERIAL_TB
VALUES (1, TIMESTAMPADD(WEEK , -12, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 'REFRIGERATOR', '010-2293-5028',
        2, 1),
       (2, TIMESTAMPADD(WEEK , -11, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 'REFRIGERATOR', '010-1212-1212',
        2, 2),
       (3, TIMESTAMPADD(WEEK , -10, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 'REFRIGERATOR', '010-2293-5028',
        2, 3),
         (4, TIMESTAMPADD(WEEK , -9, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 'REFRIGERATOR', '010-2293-5028',
        2, 4),
         (5, TIMESTAMPADD(WEEK , -8, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 'REFRIGERATOR', '010-2293-5028',
        2, 5),
         (6, TIMESTAMPADD(WEEK , -7, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 'REFRIGERATOR', '010-2293-5028',
        2, 6),
         (7, TIMESTAMPADD(WEEK , -6, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 'REFRIGERATOR', '010-2293-5028',
        2, 7),
         (8, TIMESTAMPADD(WEEK , -5, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 'REFRIGERATOR', '010-2293-5028',
        2, 8),
         (9, TIMESTAMPADD(WEEK , -4, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 'REFRIGERATOR', '010-2293-5028',
        2, 9);


-- Insert images into IMAGE_TB
INSERT INTO IMAGE_TB
VALUES (1, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator1.jpeg', 1),
       (2, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator2.jpeg', 2),
       (3, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator3.jpeg', 3),
       (4, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator4.jpeg', 4),
       (5, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator5.jpeg', 5),
       (6, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator6.jpeg', 6),
       (7, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator7.jpeg', 7),
       (8, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator8.jpeg', 8),
       (9, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator9.jpeg', 9),
         (10, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator10.png', 1),
         (11, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator11.png', 2),
         (12, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator12.png', 3),
         (13, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator13.png', 4),
         (14, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator14.png', 5),
         (15, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator15.png', 6),
         (16, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator16.png', 7),
         (17, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator17.png', 8),
         (18, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator18.png', 9),
         (19, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator19.png', 1),
         (20, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator20.png', 1),
         (21, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator21.png', 1),
         (22, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator22.png', 2),
         (23, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator23.png', 2),
         (24, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator24.png', 2),
         (25, TIMESTAMPADD(MINUTE, -30, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP),'refrigerator25.png', 3);


-- Insert trades into TRADE_TB
INSERT INTO TRADE_TB
VALUES (1, TIMESTAMPADD(WEEK , -12, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 1, 1, 'REFRIGERATOR', 1, 2),
       (2, TIMESTAMPADD(WEEK , -11, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 1, 1, 'REFRIGERATOR', 2, 2),
         (3, TIMESTAMPADD(WEEK , -10, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 1, 1, 'REFRIGERATOR', 3, 2),
         (4, TIMESTAMPADD(WEEK , -9, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 1, 1, 'REFRIGERATOR', 4, 2),
         (5, TIMESTAMPADD(WEEK , -8, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 1, 1, 'REFRIGERATOR', 5, 2),
         (6, TIMESTAMPADD(WEEK , -7, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 1, 1, 'REFRIGERATOR', 6, 2),
         (7, TIMESTAMPADD(WEEK , -6, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 1, 1, 'REFRIGERATOR', 7, 2),
         (8, TIMESTAMPADD(WEEK , -5, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 1, 1, 'REFRIGERATOR', 8, 2),
         (9, TIMESTAMPADD(WEEK , -4, CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, 30, CURRENT_TIMESTAMP), 1, 1, 'REFRIGERATOR', 9, 2);

-- Insert actions into ACTION_TB

-- Insert auctions into AUCTION_TB
INSERT INTO AUCTION_TB
VALUES (1, TIMESTAMPADD(DAY, 1, CURRENT_TIMESTAMP), CURRENT_TIMESTAMP, 5, 10000, 500000, 0, 2, 1),
       (2, TIMESTAMPADD(DAY, 2, CURRENT_TIMESTAMP), CURRENT_TIMESTAMP, 10, 10000, 600000, 0, 2, 2),
       (3, TIMESTAMPADD(DAY, 3, CURRENT_TIMESTAMP), CURRENT_TIMESTAMP, 15, 10000, 700000, 0, 2, 3);

