use resellers;


CREATE TABLE `MEMBER_TB` (
    `MEMBER_PK` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `MEMBER_NAME` VARCHAR(255) NOT NULL,
    `CREATED_DATE`    datetime(6)  NOT NULL,
    `UPDATED_DATE`    datetime(6)  NOT NULL,
     PRIMARY KEY (`MEMBER_PK`)
) ENGINE=InnoDB;

CREATE TABLE `MATERIAL_TB` (
   `MATERIAL_PK` BIGINT AUTO_INCREMENT PRIMARY KEY,
   `MEMBER_FK` BIGINT,
   `MATERIAL_TITLE` VARCHAR(255),
   `MATERIAL_JOB_TYPE` VARCHAR(255),
   `CREATED_DATE`    datetime(6)  NOT NULL,
   `UPDATED_DATE`    datetime(6)  NOT NULL,
   PRIMARY KEY (`MATERIAL_PK`),
   FOREIGN KEY (`MEMBER_FK`) REFERENCES `MEMBER_TB`(`MEMBER_PK`)
) ENGINE=InnoDB;

CREATE TABLE `PRODUCT_TB` (
    `PRODUCT_PK` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `MATERIAL_FK` BIGINT,
    `PRODUCT_NAME` VARCHAR(255) NOT NULL,
    `PRODUCT_PRICE` BIGINT NOT NULL,
    `PRODUCT_DESCRIPTION` VARCHAR(255) NOT NULL,
    `PRODUCT_BUYER` BIGINT,
    `PRODUCT_SELLER` BIGINT NOT NULL,
    `CREATED_DATE`    datetime(6)  NOT NULL,
    `UPDATED_DATE`    datetime(6)  NOT NULL,
    PRIMARY KEY (`PRODUCT_PK`),
    FOREIGN KEY (`MATERIAL_FK`) REFERENCES `MATERIAL_TB`(`MATERIAL_PK`)
) ENGINE=InnoDB;


CREATE TABLE `IMAGE_TB` (
    `IMAGE_PK` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `PRODUCT_FK` BIGINT,
    `CREATED_DATE`    datetime(6)  NOT NULL,
    `UPDATED_DATE`    datetime(6)  NOT NULL,
    PRIMARY KEY (`IMAGE_PK`),
    FOREIGN KEY (`PRODUCT_FK`) REFERENCES `PRODUCT_TB`(`PRODUCT_PK`)
) ENGINE=InnoDB;


