-- Use resellers database
USE resellers;

-- Insert members into MEMBER_TB
INSERT INTO MEMBER_TB
VALUES
    (1, '이진혁', TIMESTAMPADD(MINUTE, -30, CURRENT_TIME), TIMESTAMPADD(MINUTE, 30, CURRENT_TIME), '98102214801017', '기업은행', '010-2293-5028'),
    (2, '황대선', TIMESTAMPADD(MINUTE, -30, CURRENT_TIME), TIMESTAMPADD(MINUTE, 30, CURRENT_TIME), '1231231231', '기업은행', '010-1212-1212');

-- Insert materials into MATERIAL_TB
INSERT INTO MATERIAL_TB
VALUES
    (1, TIMESTAMPADD(MINUTE, -30, CURRENT_TIME), TIMESTAMPADD(MINUTE, 30, CURRENT_TIME), 'FOOD', '응애', 1, NULL),
    (2, TIMESTAMPADD(MINUTE, -30, CURRENT_TIME), TIMESTAMPADD(MINUTE, 30, CURRENT_TIME), 'FOOD', '응애2', 2, NULL),
    (3, TIMESTAMPADD(MINUTE, -30, CURRENT_TIME), TIMESTAMPADD(MINUTE, 30, CURRENT_TIME), 'FOOD', '응애3', 1, NULL);

-- Insert products into PRODUCT_TB
INSERT INTO PRODUCT_TB
VALUES
    (1, TIMESTAMPADD(MINUTE, -30, CURRENT_TIME), TIMESTAMPADD(MINUTE, 30, CURRENT_TIME), '상품설명', '상품이름', 1000, 2, 20, FALSE, 1),
    (2, TIMESTAMPADD(MINUTE, -30, CURRENT_TIME), TIMESTAMPADD(MINUTE, 30, CURRENT_TIME), '상품설명2', '상품이름2', 2000, 1, 10, FALSE, 2),
    (3, TIMESTAMPADD(MINUTE, -30, CURRENT_TIME), TIMESTAMPADD(MINUTE, 30, CURRENT_TIME), '상품설명3', '상품이름3', 3000, 1, 30, FALSE, 3),
    (4, TIMESTAMPADD(MINUTE, -30, CURRENT_TIME), TIMESTAMPADD(MINUTE, 30, CURRENT_TIME), '상품설명3', '상품이름3', 4000, 1, 50, FALSE, 1);

-- Insert images into IMAGE_TB
INSERT INTO IMAGE_TB
VALUES
    (1, TIMESTAMPADD(MINUTE, -30, CURRENT_TIME), TIMESTAMPADD(MINUTE, 30, CURRENT_TIME), 1),
    (2, TIMESTAMPADD(MINUTE, -30, CURRENT_TIME), TIMESTAMPADD(MINUTE, 30, CURRENT_TIME), 1),
    (3, TIMESTAMPADD(MINUTE, -30, CURRENT_TIME), TIMESTAMPADD(MINUTE, 30, CURRENT_TIME), 1);

-- Insert trades into TRADE_TB
INSERT INTO TRADE_TB
VALUES
    (1, TIMESTAMPADD(MINUTE, -30, CURRENT_TIME), TIMESTAMPADD(MINUTE, 30, CURRENT_TIME), 0, 20, 1, 1);
