version: '3'
services:
  resellers-mariadb:
    image: mariadb:10.6
    container_name: resellers-mariadb
    ports:
      - 3306:3306
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--lower_case_table_names=1", "--max_connections=2048", "--wait_timeout=3600" ]
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Seoul

  resellers-adminer:
    container_name: resellers-adminer
    image: adminer:4
    ports:
      - 18080:8080
    depends_on:
      - resellers-mariadb
    links:
      - resellers-mariadb

